spring:
   application:
         name: activity-service
   data:
     mongodb:
       uri: mongodb://mongo-db:27017/fitnessactivity
       database: fitnessactivity
server:
  port: 4001
eureka:
 client:
   service-url:
     defaultZone: http://eureka-server:8761/eureka/

 instance:
   preferIpAddress: true
   ip-address: host.docker.internal
logging:
  level:
    root: INFO
