spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    connection-timeout: 20000


  application:
         name: activity-service
  data:
     mongodb:
       uri: mongodb://localhost:27017/fitnessactivity
       database: fitnessactivity
server:
  port: 4001
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/

 #instance:
   #preferIpAddress: true
   #ip-address: host.docker.internal
logging:
  level:
    root: INFO

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking



