spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    connection-timeout: 20000




  data:
     mongodb:
       uri: mongodb://localhost:27017/fitnessactivity
       database: fitnessactivity
server:
  port: 4001
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/

 #instance:
   #preferIpAddress: true
   #ip-address: host.docker.internal
logging:
  level:
    root: INFO

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


#  Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,shutdown, refresh, health, info
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    circuitbreakers:
      enabled: true
    refresh:
      enabled: true

    info:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userValidationService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
