spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/fitness-oath2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          order: 1
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**

        - id: user-service_info
          uri: lb://USER-SERVICE
          order: 0
          predicates:
              - Path=/api/users/actuator/**
          filters:
              - StripPrefix=2
server:
  port: 4004






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG
