spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/fitness-oath2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          order: 1
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          order: 1
          predicates:
            - Path=/api/activities/**
          filters:
            - name: CircuitBreaker
              args:
                name: activityServiceCircuitBreaker
                fallbackUri: forward:/fallback/activity-service

        - id: ai-service
          uri: lb://AI-SERVICE
          order: 1
          predicates:
            - Path=/api/recommendations/**
          filters:
            - name: CircuitBreaker
              args:
                name: aiServiceCircuitBreaker
                fallbackUri: forward:/fallback/ai-service


        - id: user-service_info
          uri: lb://USER-SERVICE
          order: 0
          predicates:
              - Path=/api/users/actuator/**
          filters:
              - StripPrefix=2

        - id: activity-service-info
          uri: lb://ACTIVITY-SERVICE
          order: 0
          predicates:
                  - Path=/api/activities/actuator/**
          filters:
                  - StripPrefix=2

        - id: ai-service-info
          uri: lb://AI-SERVICE
          order: 0
          predicates:
            - Path=/api/recommendations/actuator/**
          filters:
            - StripPrefix=2

server:
  port: 4004






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



resilience4j:
  circuitbreaker:
    instances:
      userValidationService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      userValidationServiceRegister:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 40
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      activityServiceCircuitBreaker:
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true

      aiServiceCircuitBreaker:
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true

#  retry:
#    instances:
#      userValidationRetry:
#        max-attempts: 5
#        wait-duration: 2s
#        retry-exceptions:
#          - java.lang.IllegalStateException
#          - org.springframework.web.reactive.function.client.WebClientRequestException
#          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
#
#      userRegisterRetry:
#        max-attempts: 5
#        wait-duration: 2s
#        retry-exceptions:
#          - java.lang.IllegalStateException
#          - org.springframework.web.reactive.function.client.WebClientRequestException
#          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable

# ✅ Actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,info
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true

