spring:
  application:
        name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity

server:
  port: 4002
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    #instance:
     # preferIpAddress: true
      #ip-address: host.docker.internal

logging:
    level:
      root: INFO
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


