spring:
  application:
     name: configserver


  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Narasimha-prog/config_server_properties.git
server:
  port: 4003


management:
  endpoints:
    web:
      exposure:
        include: health, info, env, configprops, refresh