spring:
  application:
       name: user-service
  datasource:
    url: jdbc:postgresql://user-service-db:5432/db
    username: admin_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: host.docker.internal

logging:
  level:
    root: INFO
